# Task1

1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def division(x,y):
    try:
        ans = x/y
        return ans
    except:
        print('incorrect input')

In [2]:
division(5,0)

incorrect input


In [4]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for s in subjects:
    for v in verbs:
        for o in objects:
            print (s,v,o)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task2

In [2]:
import numpy as np
inp = input('Enter a list of values: ')
times = int(input('Upto power : '))
increasing = input('Enter boolean for increasing : ')
inp = inp.split(' ')
V =[]
for i in inp:
    V.append(int(i))
if increasing == 'True':
    A = np.array([j**k for j in V for k in range(times)]).reshape(len(V),-1)
else:
    A = np.array([j ** k for j in V for k in range(times-1,-1,-1)]).reshape(len(V), -1)
print(A)

Enter a list of values: 1 2 3 4 5 6
Upto power : 3
Enter boolean for increasing : False
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]
 [36  6  1]]
